# Generated by Django 4.2.1 on 2023-05-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField()),
                ('created_at', models.TextField()),
                ('location', models.TextField()),
                ('company', models.TextField()),
                ('source', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
    ]
